# Autogenerated wrapper script for GAP_pkg_guava_jll for x86_64-linux-musl
export desauto, leonconv, minimum_weight, wtdist

JLLWrappers.@generate_wrapper_header("GAP_pkg_guava")
JLLWrappers.@declare_executable_product(desauto)
JLLWrappers.@declare_executable_product(leonconv)
JLLWrappers.@declare_executable_product(minimum_weight)
JLLWrappers.@declare_executable_product(wtdist)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        desauto,
        "bin/desauto",
    )

    JLLWrappers.@init_executable_product(
        leonconv,
        "bin/leonconv",
    )

    JLLWrappers.@init_executable_product(
        minimum_weight,
        "bin/minimum-weight",
    )

    JLLWrappers.@init_executable_product(
        wtdist,
        "bin/wtdist",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
